// This file is auto-generated by scripts/generate-font-imports.js
// DO NOT EDIT MANUALLY

// @ts-ignore
import inter_italic_ttf from "./inter/italic.ttf";
// @ts-ignore
import inter_regular_ttf from "./inter/regular.ttf";

export interface FontImport {
  name: string;
  family: string;
  data: string;
  fileName: string;
  isVariable: boolean;
  weights: number | { min: number; max: number; default: number };
  hasItalic: boolean;
}

export const fontImports: FontImport[] = [
  {
    name: "inter_italic_ttf",
    family: "Inter",
    data: typeof inter_italic_ttf === 'string' ? inter_italic_ttf.split(',')[1] || inter_italic_ttf : inter_italic_ttf,
    fileName: "italic.ttf",
    isVariable: true,
    weights: { min: 100, max: 900, default: 400 },
    hasItalic: true
  },
  {
    name: "inter_regular_ttf",
    family: "Inter",
    data: typeof inter_regular_ttf === 'string' ? inter_regular_ttf.split(',')[1] || inter_regular_ttf : inter_regular_ttf,
    fileName: "regular.ttf",
    isVariable: true,
    weights: { min: 100, max: 900, default: 400 },
    hasItalic: false
  },
];
